import { Worker, MessageChannel, receiveMessageOnPort } from 'node:worker_threads';

// Tokenize quoted strings/comments before translating SQL; a question mark in
// an author's text or a timestamp format must never become a bind parameter.
export function sqlFragments(sql) {
  return String(sql).match(/'(?:''|[^'])*'|"(?:""|[^"])*"|--[^\n]*(?:\n|$)|\/\*[\s\S]*?\*\/|[^'"/-]+|[-/]/g) || [];
}
export function splitStatements(sql) {
  const statements = []; let pending = '';
  for (const fragment of sqlFragments(sql)) {
    if (/^['"]/.test(fragment)) { pending += fragment; continue; }
    if (/^--|^\/\*/.test(fragment)) { pending += ' '; continue; }
    const parts = fragment.split(';'); pending += parts.shift();
    for (const part of parts) { if (pending.trim()) statements.push(pending.trim()); pending = part; }
  }
  if (pending.trim()) statements.push(pending.trim());
  return statements;
}
const utcNow = `to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')`;
export function translateSql(source) {
  let sql = String(source).trim().replace(/;\s*$/, '');
  sql = sql.replace(/strftime\('%Y-%m-%dT%H:%M:%fZ'\s*,\s*'now'\)/gi, utcNow)
    .replace(/datetime\('now'\)/gi, utcNow)
    .replace(/json_valid\((\w+)\)/gi, '($1 IS JSON)')
    .replace(/json_extract\((\w+),\s*'\$\.(\w+)'\)/gi, "($1::jsonb ->> '$2')")
    .replace(/\bIS\s*\?/gi, 'IS NOT DISTINCT FROM ?')
    .replace(/\bGLOB\s*'\?\?\?\?-\?\?-\?\? \?\?:\?\?:\?\?'/gi, "LIKE '____-__-__ __:__:__'")
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/gi, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/\bid INTEGER PRIMARY KEY(?!\s+AUTOINCREMENT)/gi, 'id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/ALTER TABLE (\w+) ADD COLUMN /gi, 'ALTER TABLE $1 ADD COLUMN IF NOT EXISTS ');
  const ignore = /^INSERT OR IGNORE\b/i.test(sql);
  if (ignore) sql = sql.replace(/^INSERT OR IGNORE/i, 'INSERT');
  const replacement = sql.match(/^INSERT OR REPLACE INTO (\w+)\s*\(([^)]+)\)/i);
  if (replacement) {
    const columns = replacement[2].split(',').map(column => column.trim());
    if (!columns.includes('id')) throw Error('Unsupported replacement without explicit primary key');
    sql = sql.replace(/^INSERT OR REPLACE/i, 'INSERT') + ' ON CONFLICT(id) DO UPDATE SET ' + columns.filter(column => column !== 'id').map(column => `${column}=excluded.${column}`).join(',');
  }
  if (ignore) {
    const returning = sql.search(/\bRETURNING\b/i);
    sql = returning >= 0 ? sql.slice(0, returning) + ' ON CONFLICT DO NOTHING ' + sql.slice(returning) : sql + ' ON CONFLICT DO NOTHING';
  }
  const upsertTable = sql.match(/^INSERT INTO ["']?(\w+)["']?[\s\S]*ON CONFLICT[\s\S]*DO UPDATE SET/i)?.[1];
  if (upsertTable) {
    const updateStart = sql.search(/DO UPDATE SET/i) + 'DO UPDATE SET'.length;
    sql = sql.slice(0, updateStart) + sqlFragments(sql.slice(updateStart)).map(fragment => /^['"]/.test(fragment) ? fragment
      : fragment.replace(/(?<![\w.])(revision|count|expires_at)(?!\w|\s*=)/g, `${upsertTable}.$1`)).join('');
  }
  let index = 0;
  const definition = /^(CREATE|ALTER) TABLE/i.test(sql);
  let compiled = sqlFragments(sql).map(fragment => {
    if (/^['"]|^--|^\/\*/.test(fragment)) return fragment;
    if (definition) fragment = fragment.replace(/\bINTEGER\b/gi, 'BIGINT').replace(/\bREAL\b/gi, 'DOUBLE PRECISION')
      .replace(/REFERENCES (\w+)\(([^)]+)\)(\s+ON DELETE (?:CASCADE|SET NULL|RESTRICT|NO ACTION))?(?!\s+DEFERRABLE)/gi, 'REFERENCES $1($2)$3 DEFERRABLE INITIALLY IMMEDIATE');
    return fragment.replace(/\binstr\s*\(/gi, 'strpos(').replace(/\?/g, () => '$' + ++index);
  }).join('');
  const lexical = compiled.match(/library_index_fts\s+MATCH\s+(\$\d+|'(?:''|[^'])*')/i);
  if (lexical) {
    const query = `websearch_to_tsquery('simple',${lexical[1]})`;
    compiled = compiled.replace(lexical[0], `to_tsvector('simple',tokens) @@ ${query}`)
      .replace(/bm25\(library_index_fts\)/gi, `-ts_rank_cd(to_tsvector('simple',tokens),${query})`);
  }
  return compiled;
}

export class PostgresDatabase {
  constructor(connectionString, schema) {
    if (!/^nk_[a-z0-9_]{1,58}$/.test(schema)) throw Error('Invalid Novel-King database schema');
    this.kind = 'postgres'; this.schema = schema; this.isTransaction = false; this.closed = false;
    const channel = new MessageChannel(); this.port = channel.port1;
    this.signal = new Int32Array(new SharedArrayBuffer(4));
    this.worker = new Worker(new URL('./postgres-worker.mjs', import.meta.url), {
      workerData: { connectionString, schema, port: channel.port2, signal: this.signal.buffer }, transferList: [channel.port2]
    });
    this.worker.on('error', () => {});
    this.receive();
  }
  receive() {
    if (Atomics.wait(this.signal, 0, 0, 30000) === 'timed-out') {
      this.worker.terminate(); this.closed = true; throw Error('PostgreSQL operation timed out; database connection closed');
    }
    const message = receiveMessageOnPort(this.port)?.message;
    if (!message) throw Error('Missing PostgreSQL response');
    if (message.error) throw Object.assign(new Error(message.error), { code: message.code });
    return message;
  }
  request(request) {
    if (this.closed) throw Error('Database closed');
    Atomics.store(this.signal, 0, 0); this.port.postMessage(request); return this.receive();
  }
  prepare(source) {
    const pragma = source.match(/^\s*PRAGMA table_info\(["']?(\w+)["']?\)\s*;?$/i);
    const query = (...parameters) => {
      if (pragma) return this.request({ columns: pragma[1] });
      const insertTable = source.match(/^\s*INSERT(?: OR IGNORE| OR REPLACE)? INTO\s+["']?(\w+)/i)?.[1];
      return this.request({ sql: translateSql(source), parameters: parameters.map(value => value === undefined ? null : typeof value === 'bigint' ? value.toString() : value), insertTable });
    };
    return { all: (...parameters) => query(...parameters).rows, get: (...parameters) => query(...parameters).rows[0],
      run: (...parameters) => { const response = query(...parameters); return { changes: response.rowCount, lastInsertRowid: response.rows[0]?.id ?? 0 }; } };
  }
  exec(source) {
    if (/^\s*CREATE TRIGGER IF NOT EXISTS works_assign_ov_uri\b/i.test(source)) {
      this.request({ sql: `ALTER TABLE works ALTER COLUMN ov_uri SET DEFAULT md5(gen_random_uuid()::text)`, parameters: [] }); return;
    }
    for (const statement of splitStatements(source)) {
      if (/^PRAGMA (journal_mode|foreign_keys|busy_timeout)\b/i.test(statement)) continue;
      if (/CREATE VIRTUAL TABLE.*library_index_fts/i.test(statement)) {
        this.request({ sql: 'CREATE TABLE IF NOT EXISTS library_index_fts(tokens TEXT,doc_id BIGINT)', parameters: [] });
        this.request({ sql: "CREATE INDEX IF NOT EXISTS idx_library_lexical ON library_index_fts USING GIN(to_tsvector('simple',tokens))", parameters: [] }); continue;
      }
      this.request({ sql: translateSql(statement), parameters: [] });
      if (/^BEGIN\b/i.test(statement)) this.isTransaction = true;
      if (/^(COMMIT|ROLLBACK$)/i.test(statement)) this.isTransaction = false;
    }
  }
  close() {
    if (this.closed) return;
    try { this.request({ close: true }); } finally { this.closed = true; this.port.close(); this.worker.terminate(); }
  }
}
